export const USER_BVN_VALIDATION_REQUEST = "USER_BVN_VALIDATION_REQUEST";
export const USER_BVN_VALIDATION_SUCCESS = "USER_BVN_VALIDATION_SUCCESS";
export const USER_BVN_VALIDATION_FAIL = "USER_BVN_VALIDATION_FAIL";

export const USER_ACCEPT_TERMS_REQUEST = "USER_ACCEPT_TERMS_REQUEST";
export const USER_ACCEPT_TERMS_SUCCESS = "USER_ACCEPT_TERMS_SUCCESS";
export const USER_ACCEPT_TERMS_FAIL = "USER_ACCEPT_TERMS_FAIL";
export const USER_ACCEPT_TERMS_RESET = "USER_ACCEPT_TERMS_RESET";

export const USER_REJECT_TERMS_REQUEST = "USER_REJECT_TERMS_REQUEST";
export const USER_REJECT_TERMS_SUCCESS = "USER_REJECT_TERMS_SUCCESS";
export const USER_REJECT_TERMS_FAIL = "USER_REJECT_TERMS_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_BANK_REQUEST = "USER_UPDATE_BANK_REQUEST";
export const USER_UPDATE_BANK_SUCCESS = "USER_UPDATE_BANK_SUCCESS";
export const USER_UPDATE_BANK_FAIL = "USER_UPDATE_BANK_FAIL";
export const USER_UPDATE_BANK_RESET = "USER_UPDATE_BANK_RESET";

export const USER_UPDATE_DETAILS_REQUEST = "USER_UPDATE_DETAILS_REQUEST";
export const USER_UPDATE_DETAILS_SUCCESS = "USER_UPDATE_DETAILS_SUCCESS";
export const USER_UPDATE_DETAILS_FAIL = "USER_UPDATE_DETAILS_FAIL";

export const USER_ADD_NEWBANK_REQUEST = "USER_ADD_NEWBANK_REQUEST";
export const USER_ADD_NEWBANK_SUCCESS = "USER_ADD_NEWBANK_SUCCESS";
export const USER_ADD_NEWBANK_FAIL = "USER_ADD_NEWBANK_FAIL";
export const USER_ADD_NEWBANK_RESET = "USER_ADD_NEWBANK_RESET";
