export const USER_BVN_VALIDATION_REQUEST = "USER_BVN_VALIDATION_REQUEST";
export const USER_BVN_VALIDATION_SUCCESS = "USER_BVN_VALIDATION_SUCCESS";
export const USER_BVN_VALIDATION_FAIL = "USER_BVN_VALIDATION_FAIL";

export const USER_ACCEPT_TERMS_REQUEST = "USER_ACCEPT_TERMS_REQUEST";
export const USER_ACCEPT_TERMS_SUCCESS = "USER_ACCEPT_TERMS_SUCCESS";
export const USER_ACCEPT_TERMS_FAIL = "USER_ACCEPT_TERMS_FAIL";

export const USER_REJECT_TERMS_REQUEST = "USER_REJECT_TERMS_REQUEST";
export const USER_REJECT_TERMS_SUCCESS = "USER_REJECT_TERMS_SUCCESS";
export const USER_REJECT_TERMS_FAIL = "USER_REJECT_TERMS_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_UPDATE_BANK_REQUEST = "USER_UPDATE_BANK_REQUEST";
export const USER_UPDATE_BANK_SUCCESS = "USER_UPDATE_BANK_SUCCESS";
export const USER_UPDATE_BANK_FAIL = "USER_UPDATE_BANK_FAIL";
